import { useQuery } from "@tanstack/react-query";
import Head from "next/head";
import { fetchPosts } from "@/pages/api/hello";
import PostList from "@/components/postList";

export default function Home() {
  // const { data, isLoading, status } = useQuery({
  //   queryKey: ["posts"],
  //   queryFn: fetchPosts,
  // });

  // console.log(data, isLoading, status);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 className="title">My Books</h2>
        <PostList />
      </main>
    </>
  );
}
